package presentacion;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica_negocio.GestorSesiones;
import logica_negocio.Sesion;
import utilidades.Utilidades;

/**
 *
 * @author Alexander Inagan
 */
public class GUISesiones extends javax.swing.JInternalFrame {

    private final GestorSesiones gestor_sesiones = new GestorSesiones();
    /**
     * Creates new form GUISesiones
     */
    public GUISesiones() {
        initComponents();
        inicializarTabla();
    }
    
    private void inicializarTabla() {

        jtblSesiones.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre Usuario", "Contraseña", "Fecha/Hora", "Ingreso Valido"
                }
        ));
    }
    
    private String getNombre_user() {
        return jtxtUsuario.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNorte = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPorUsuario = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jbtnConsulrar = new javax.swing.JButton();
        jLabelTodos = new javax.swing.JLabel();
        jbtnConsultar_todo = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblSesiones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sesiones");

        jPanelNorte.setBackground(new java.awt.Color(181, 120, 120));
        jPanelNorte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Información: "));

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        jLabelTitulo.setText("Informe de Sesiones");
        jPanelNorte.add(jLabelTitulo);

        getContentPane().add(jPanelNorte, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(0, 117, 220));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos: \n"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(122, 245, 196));
        jPanel2.setLayout(new java.awt.GridLayout(2, 3));

        jLabelPorUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPorUsuario.setText("Sesiones de un Usuario: ");
        jLabelPorUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.darkGray));
        jPanel2.add(jLabelPorUsuario);
        jPanel2.add(jtxtUsuario);

        jbtnConsulrar.setBackground(new java.awt.Color(102, 204, 255));
        jbtnConsulrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnConsulrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        jbtnConsulrar.setText("Consultar");
        jbtnConsulrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsulrarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConsulrar);

        jLabelTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTodos.setText("Todos los registros: ");
        jLabelTodos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.darkGray));
        jPanel2.add(jLabelTodos);

        jbtnConsultar_todo.setBackground(new java.awt.Color(206, 159, 159));
        jbtnConsultar_todo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnConsultar_todo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        jbtnConsultar_todo.setText("Consultar Todo");
        jbtnConsultar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultar_todoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConsultar_todo);

        jButtonCerrar.setBackground(new java.awt.Color(220, 95, 95));
        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar.png"))); // NOI18N
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCerrar);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanelDatos.setBackground(new java.awt.Color(0, 117, 220));
        jPanelDatos.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 117, 220));

        jtblSesiones.setBackground(new java.awt.Color(147, 196, 212));
        jtblSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblSesiones);

        jPanelDatos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelDatos, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConsulrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsulrarActionPerformed
        String usuario_name = jtxtUsuario.getText().trim();
        if(usuario_name.equals(""))
        {
            Utilidades.mensajeAdvertencia("Debe ingresar un nombre de Usuario", "Advertencia");
            jtxtUsuario.requestFocus();
        }
        ArrayList<Sesion> lista_sesiones = gestor_sesiones.obtener_sesiones_por_usuario(usuario_name);
        
        if(lista_sesiones.isEmpty())
        {
            Utilidades.mensajeError("Este usuario no tiene registros o no existe.", "Informe");
            jtxtUsuario.setText("");
        }
        else
        {
            llenarTabla(lista_sesiones);
            jtxtUsuario.setText("");
        }
        
    }//GEN-LAST:event_jbtnConsulrarActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jbtnConsultar_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultar_todoActionPerformed
        ArrayList<Sesion> lista_sesiones = gestor_sesiones.obtener_todas_sesiones();
        
        if(lista_sesiones.isEmpty())
        {
            Utilidades.mensajeError("Este usuario no tiene registros o no existe.", "Informe");
            jtxtUsuario.setText("");
        }
        else
        {
            llenarTabla(lista_sesiones);
            jtxtUsuario.setText("");
        }
    }//GEN-LAST:event_jbtnConsultar_todoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUISesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUISesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUISesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUISesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUISesiones().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabelPorUsuario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelNorte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConsulrar;
    private javax.swing.JButton jbtnConsultar_todo;
    private javax.swing.JTable jtblSesiones;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla(ArrayList<Sesion> lista_sesiones)
    {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) jtblSesiones.getModel();

        Object rowData[] = new Object[4];
        for(Sesion sesion : lista_sesiones) {
            rowData[0] = sesion.getUsuario();
            rowData[1] = sesion.getContrasenia();
            rowData[2] = sesion.getFecha_hora();
            rowData[3] = sesion.getIngreso_valido();
            model.addRow(rowData);
        }
    }
}
